---
- name: Set Facts Job1 Workflow1
  hosts: all
  gather_facts: False
  vars:
    ANSIBLE_SHOW_CUSTOM_STATS: true
  tasks:
    - name: Set Facts 
      ansible.builtin.set_fact:
        fact1_job1_wf1: "This is set fact at Fact1 Job1 WF1"

    - name: Set Facts Cached
      ansible.builtin.set_fact:
        fact2_job1_wf1: "This is set fact cached at Fact2 Job1 WF1"
        cacheable: yes

    - name: Set Stats default
      ansible.builtin.set_stats:
        data:
          stat1_job1_wf1: "This is set stat at Stat1 Job1 WF1"
        aggregate: True

    - name: Set Stats no agg no host
      ansible.builtin.set_stats:
        data:
          stat2_job1_wf1: "This is set stat cached at Stat2 Job1 WF1"
        aggregate: False

    - name: Print Vars
      debug:
        msg:
          - "Fact1 Job1 WF1 {{ fact1_job1_wf1 | default('not set') }}"
          - "Fact2 Job1 WF1 {{ fact2_job1_wf1 | default('not set') }}"
          - "Stat1 Job1 WF1 {{ stat1_job1_wf1 | default('not set') }}"
          - "Stat2 Job1 WF1 {{ stat2_job1_wf1 | default('not set') }}"

