---
- name: Set Facts Job1 Workflow2
  hosts: all
  gather_facts: False
  vars:
    ANSIBLE_SHOW_CUSTOM_STATS: true
  tasks:

    - name: Print Vars
      debug:
        msg:
          - "Fact1 Job1 WF1 {{ fact1_job1_wf1 | default('not set') }}"
          - "Fact2 Job1 WF1 {{ fact2_job1_wf1 | default('not set') }}"
          - "Stat1 Job1 WF1 {{ stat1_job1_wf1 | default('not set') }}"
          - "Stat2 Job1 WF1 {{ stat2_job1_wf1 | default('not set') }}"
          - "Fact3 Job2 WF1 {{ fact3_job2_wf1 | default('not set') }}"
          - "Fact4 Job2 WF1 {{ fact4_job2_wf1 | default('not set') }}"
          - "Stat3 Job2 WF1 {{ stat3_job2_wf1 | default('not set') }}"
          - "Stat4 Job2 WF1 {{ stat4_job2_wf1 | default('not set') }}"

    - name: Set Facts 
      ansible.builtin.set_fact:
        fact5_job1_wf2: "This is set fact at Fact5 Job1 WF2"

    - name: Set Facts Cached
      ansible.builtin.set_fact:
        fact6_job1_wf2: "This is set fact cached at Fact6 Job1 WF2"
        cacheable: yes

    - name: Set Stats default
      ansible.builtin.set_stats:
        data:
          stat5_job1_wf2: "This is set stat at Stat5 Job1 WF2"
        aggregate: yes

    - name: Set Stats no agg no host
      ansible.builtin.set_stats:
        data:
          stat6_job1_wf2: "This is set stat cached at Stat6 Job1 WF2"
        per_host: no
        aggregate: no

    - name: Print Vars
      debug:
        msg:
          - "Fact1 Job1 WF1 {{ fact1_job1_wf1 | default('not set') }}"
          - "Fact2 Job1 WF1 {{ fact2_job1_wf1 | default('not set') }}"
          - "Stat1 Job1 WF1 {{ stat1_job1_wf1 | default('not set') }}"
          - "Stat2 Job1 WF1 {{ stat2_job1_wf1 | default('not set') }}"
          - "Fact3 Job2 WF1 {{ fact3_job2_wf1 | default('not set') }}"
          - "Fact4 Job2 WF1 {{ fact4_job2_wf1 | default('not set') }}"
          - "Stat3 Job2 WF1 {{ stat3_job2_wf1 | default('not set') }}"
          - "Stat4 Job2 WF1 {{ stat4_job2_wf1 | default('not set') }}"
          - "Fact5 Job1 WF2 {{ fact5_job1_wf2 | default('not set') }}"
          - "Fact6 Job1 WF2 {{ fact6_job1_wf2 | default('not set') }}"
          - "Stat5 Job1 WF2 {{ stat5_job1_wf2 | default('not set') }}"
          - "Stat6 Job1 WF2 {{ stat6_job1_wf2 | default('not set') }}"


