---
- name: Set Facts Job2 Workflow1
  hosts: all
  gather_facts: False
  vars:
    ANSIBLE_SHOW_CUSTOM_STATS: true
  tasks:
    - name: Print Vars before
      debug:
        msg:
          - "Stat1 Job1 WF1 {{ stat1_job1_wf1 | default('not set') }}"

    - name: Set Stats j2 wf1
      ansible.builtin.set_stats:
        data:
            stat1_job1_wf1: "{{ item }}"
        per_host: no
        aggregate: yes
      loop:
        - "three job2 wf1,"
        - "four job2 wf1"


    - name: Print Vars after
      debug:
        msg:
          - "Stat1 Job1 WF1 {{ stat1_job1_wf1 | default('not set') }}"
 