---
- name: Set Facts Job2 Workflow1
  hosts: all
  gather_facts: False
  vars:
    ANSIBLE_SHOW_CUSTOM_STATS: true
  tasks:

    - name: Print Vars
      ansible.builtin.debug:
        msg:
          - "Fact1 Job1 WF1 {{ fact1_dict.fact1_job1_wf1 | default('not set') }}"
          - "Fact2 Job1 WF1 {{ fact2_job1_wf1 | default('not set') }}"
          - "Stat1 Job1 WF1 {{ stat1_dict.stat1_job1_wf1 | default('not set') }}"
          - "Stat2 Job1 WF1 {{ stat2_job1_wf1 | default('not set') }}"
          - "Stat9 Job1 WF1 {{ stat9_dict.stat9_job1_wf1 | default('not set') }}"

    - name: Set Facts 
      ansible.builtin.set_fact:
        fact3_job2_wf1: "This is set fact at Job2 WF1"

    - name: Set Facts Cached
      ansible.builtin.set_fact:
        fact4_job2_wf1: "This is set fact cached at Job2 WF1"
        cacheable: yes
        
    - name: Set Stats default
      ansible.builtin.set_stats:
        data:
            stat1_job1_wf1: "This is set stat agg at Job2 WF1"
        aggregate: yes

    - name: Set Stats 9 j2 wf1
      ansible.builtin.set_stats:
          data:
            stat9_dict:
              stat9_job1_wf1: "This is set stat agg at Job2 WF1"
          aggregate: yes

    - name: Set Stats no agg no host
      ansible.builtin.set_stats:
        data:
          stat2_job1_wf1: "This is set stat no agg at Job2 WF1"
        per_host: no
        aggregate: no

    - name: Print Vars
      debug:
        msg:
          - "Fact1 Job1 WF1 {{ fact1_dict.fact1_job1_wf1 | default('not set') }}"
          - "Fact2 Job1 WF1 {{ fact2_job1_wf1 | default('not set') }}"
          - "Stat1 Job1 WF1 {{ stat1_dict.stat1_job1_wf1 | default('not set') }}"
          - "Stat2 Job1 WF1 {{ stat2_job1_wf1 | default('not set') }}"
          - "Stat9 Job1 WF1 {{ stat9_dict.stat9_job1_wf1 | default('not set') }}"
          - "Fact3 Job2 WF1 {{ fact3_job2_wf1 | default('not set') }}"
          - "Fact4 Job2 WF1 {{ fact4_job2_wf1 | default('not set') }}"
          - "Stat3 Job2 WF1 {{ stat3_job2_wf1 | default('not set') }}"
          - "Stat4 Job2 WF1 {{ stat4_job2_wf1 | default('not set') }}"

