---
- name: Set Stats to blank
  hosts: all
  gather_facts: False
  vars:
    ANSIBLE_SHOW_CUSTOM_STATS: true
  tasks:
    # - name: Set Facts 
    #   ansible.builtin.set_fact:
    #       fact1_job1_wf1: "This is set fact at Job1 WF1"

    # - name: Set Facts Cached
    #   ansible.builtin.set_fact:
    #     fact2_job1_wf1: "This is set fact cached at Job1 WF1"
    #     cacheable: yes

    - name: Print Vars
      debug:
        msg:
          - "Stat1 Job1 WF1 {{ stat1_job1_wf1 | default('not set') }}"

    - name: Set Stats j1 wf1
      ansible.builtin.set_stats:
        data:
          stat1_job1_wf1: ""
        per_host: no
        aggregate: no

    - name: Print Vars
      debug:
        msg:
          - "Stat1 Job1 WF1 {{ stat1_job1_wf1 | default('not set') }}"
      